<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-FHVIN2VS" ignored="0" name="HubSpot Feature Testing-ContactsPage" tests="4" failures="1" timestamp="29 May 2022 23:09:02 GMT" time="19.419" errors="0">
  <testcase name="verifyContactsPageTitleTest" time="0.016" classname="com.qa.hubspot.tests.ContactsPageTest"/>
  <testcase name="verifyContactsPageHeaderTest" time="0.066" classname="com.qa.hubspot.tests.ContactsPageTest"/>
  <testcase name="createNewContactTest" time="1.909" classname="com.qa.hubspot.tests.ContactsPageTest"/>
  <testcase name="deleteAllContacts" time="5.246" classname="com.qa.hubspot.tests.ContactsPageTest">
    <failure type="java.lang.AssertionError" message="expected [No records found..] but found [No records found]">
      <![CDATA[java.lang.AssertionError: expected [No records found..] but found [No records found]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.qa.hubspot.tests.ContactsPageTest.deleteAllContacts(ContactsPageTest.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- deleteAllContacts -->
</testsuite> <!-- HubSpot Feature Testing-ContactsPage -->
